import type { Metadata } from 'next';
import './styles/globals.css';
import { Noto_Serif_Display } from 'next/font/google';
import { Inter } from 'next/font/google';
import { Poppins } from 'next/font/google';
import { ThemeProvider } from '@/components/providers/theme-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// title font for the titles (testing)
const primaryFont = Noto_Serif_Display({
  subsets: ['latin'],
  variable: '--titleFont',
});

const secondaryFont = Inter({
  subsets: ['latin'],
  variable: '--secondaryFont',
});

const HeaderFont = Poppins({
  subsets: ['latin'],
  variable: '--HeaderFont',
  weight: ["100","200","300","400","500","600","700","800","900"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`antialiased ${primaryFont.variable} ${secondaryFont.variable} ${HeaderFont.variable}`}>
      <body className="min-h-full flex flex-col dark:bg-[#000000]">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
